In [6]:
[set(x) for x in [[1,2,3]]]

[{1, 2, 3}]

In [12]:
from itertools import product

print(list((product(*[[1,2,3]]))))

[(1,), (2,), (3,)]


In [49]:
from sklearn.datasets import make_classification, make_regression, load_digits, load_boston
from sklearn.model_selection import train_test_split, GridSearchCV


digits_data = load_digits().data
digits_target = load_digits().target[:, None] # to make the targets consistent with our model interfaces
X_train, X_test, y_train, y_test = train_test_split(digits_data, digits_target, test_size=0.2)

In [50]:

# y = np.arange(4)[:, None] + np.asarray([0.2, -0.3, 0.1, 0.4])[:, None]
y = y_train

In [51]:
import functools
import numpy as np
import itertools

H = 0
for classes in itertools.product(*[set(x) for x in y]):
        v = functools.reduce(np.logical_and, ((predictions, c) for predictions, c in zip(y, classes)))
        p = np.mean(v)
        H += -p * np.log2(p) if p > 0 else 0
H

0

In [52]:
from collections import defaultdict
import math

n = len(y)
label_count = defaultdict(int)

for label in y:
        label_count[label[0]] +=1
        
entropy = 0
for label in label_count:
    prob = float(label_count[label]) / n
    entropy -= prob * math.log(prob, 2)
    
entropy

3.319900007560189

In [53]:
y

array([[5],
       [1],
       [3],
       ...,
       [3],
       [7],
       [0]])

In [58]:
np.unique([1,2,3], return_counts=True)

(array([1, 2, 3]), array([1, 1, 1]))

In [59]:
import numpy as np
from sklearn.base import BaseEstimator
from sklearn.datasets import make_classification, make_regression, load_digits, load_boston
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, mean_squared_error
import pandas as pd

digits_data = load_digits().data
digits_target = load_digits().target[:, None] # to make the targets consistent with our model interfaces
X_train, X_test, y_train, y_test = train_test_split(digits_data, digits_target, test_size=0.2)

print(len(digits_data))


1797


In [64]:
digits_target = load_digits().target[:, None] 
digits_target

IndexError: too many indices for array

In [70]:
load_digits().target[:, None]

array([[0],
       [1],
       [2],
       ...,
       [8],
       [9],
       [8]])

In [72]:
np.unique(
                    [1,2,3,4], return_counts=True)

(array([1, 2, 3, 4]), array([1, 1, 1, 1]))

In [74]:
y = np.array([1.,2.,3.])
y.astype(int)

array([1, 2, 3])

In [85]:
np.mean([[1,2,3], [4,5,6]], axis = 1)

array([2., 5.])

In [89]:
np.sort([5,12,235,11])[1:-1]

array([  5,  11,  12, 235])